// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEoTJxdYsuNODeKp7oGtWA1xLEGGZCwlI',
    appId: '1:1094180384065:web:c7bad200c3afff285005c0',
    messagingSenderId: '1094180384065',
    projectId: 'flutter-chat-d84b6',
    authDomain: 'flutter-chat-d84b6.firebaseapp.com',
    storageBucket: 'flutter-chat-d84b6.firebasestorage.app',
    measurementId: 'G-D5XLY57NQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxQeonW7tyh2zpTeQcTCOMrtyYm9f8G1o',
    appId: '1:1094180384065:android:16af48166d3be52a5005c0',
    messagingSenderId: '1094180384065',
    projectId: 'flutter-chat-d84b6',
    storageBucket: 'flutter-chat-d84b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk3oz-viW5pC0xNqbEBXh2tNbxhk1psXU',
    appId: '1:1094180384065:ios:f61eb4092fa3a3ac5005c0',
    messagingSenderId: '1094180384065',
    projectId: 'flutter-chat-d84b6',
    storageBucket: 'flutter-chat-d84b6.firebasestorage.app',
    iosBundleId: 'com.example.chtapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk3oz-viW5pC0xNqbEBXh2tNbxhk1psXU',
    appId: '1:1094180384065:ios:f61eb4092fa3a3ac5005c0',
    messagingSenderId: '1094180384065',
    projectId: 'flutter-chat-d84b6',
    storageBucket: 'flutter-chat-d84b6.firebasestorage.app',
    iosBundleId: 'com.example.chtapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEoTJxdYsuNODeKp7oGtWA1xLEGGZCwlI',
    appId: '1:1094180384065:web:47e48a7e81b8ee235005c0',
    messagingSenderId: '1094180384065',
    projectId: 'flutter-chat-d84b6',
    authDomain: 'flutter-chat-d84b6.firebaseapp.com',
    storageBucket: 'flutter-chat-d84b6.firebasestorage.app',
    measurementId: 'G-DK2GN5SJNJ',
  );

}